# TSG
title: TSG
description: 
baseurl: "/TSG" # the subpath of your site
url: "https://scott-mccann.github.io"
email: 
github_username:  scott-mccann
linkedin_username: 
twitter_username: 

# Build settings
markdown: kramdown
sass:
